package com.sunshine.cmdguard;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeSet;
import java.util.regex.Pattern;

/**
 * Builds a review-ready starter config from a live command scan.
 * Never touches the live config.yml: output goes to config.generated.yml.
 */
public final class ConfigGenerator {

    private static final Pattern SAFE = Pattern.compile("^[A-Za-z0-9_][A-Za-z0-9_.:/-]*$");

    /** Generated YAML plus counts. */
    public record Result(String yaml, int publicCommands, int restrictedCommands) {}

    private ConfigGenerator() {}

    /**
     * Splits scanned commands: no Bukkit permission -&gt; default, permission required -&gt; staff.
     * Plain (non-namespaced) aliases land in hidden so they stay runnable but invisible.
     */
    public static Result generate(Map<String, CommandScan.Entry> scan) {
        TreeSet<String> publicCmds = new TreeSet<>();
        TreeSet<String> publicHidden = new TreeSet<>();
        TreeSet<String> restrictedCmds = new TreeSet<>();
        TreeSet<String> restrictedHidden = new TreeSet<>();
        if (scan != null) {
            for (CommandScan.Entry e : scan.values()) {
                if (e == null || e.label() == null || e.label().isEmpty()) {
                    continue;
                }
                boolean restricted = e.permission() != null && !e.permission().isEmpty();
                TreeSet<String> cmds = restricted ? restrictedCmds : publicCmds;
                TreeSet<String> hid = restricted ? restrictedHidden : publicHidden;
                cmds.add(e.label());
                if (e.aliases() != null) {
                    for (String a : e.aliases()) {
                        if (a == null || a.isEmpty() || a.contains(":")) {
                            continue;
                        }
                        String n = CommandMatcher.normalize(a);
                        if (!n.isEmpty() && !cmds.contains(n)) {
                            hid.add(n);
                        }
                    }
                }
            }
        }
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by /cmdguard generate - REVIEW BEFORE USE.\n");
        sb.append("# Copy the parts you want into config.yml, then /cmdguard reload.\n");
        sb.append("# Alternative: set permission-sync: true and keep these lists tiny;\n");
        sb.append("# the plugin then also requires each command's own Bukkit permission.\n");
        sb.append("groups:\n");
        sb.append("  default:\n");
        sb.append("    priority: 0\n");
        sb.append("    blocked-message: \"<red>Unknown command.\"\n");
        appendList(sb, "    commands", new ArrayList<>(publicCmds));
        appendList(sb, "    hidden", new ArrayList<>(publicHidden));
        sb.append("    args: {}\n");
        sb.append("    worlds: []\n");
        sb.append("  staff:\n");
        sb.append("    priority: 50\n");
        sb.append("    inherit: [default]\n");
        sb.append("    blocked-message: \"<red>Unknown command.\"\n");
        appendList(sb, "    commands", new ArrayList<>(restrictedCmds));
        appendList(sb, "    hidden", new ArrayList<>(restrictedHidden));
        sb.append("    args: {}\n");
        sb.append("    worlds: []\n");
        return new Result(sb.toString(), publicCmds.size(), restrictedCmds.size());
    }

    private static void appendList(StringBuilder sb, String key, List<String> items) {
        if (items.isEmpty()) {
            sb.append(key).append(": []\n");
            return;
        }
        sb.append(key).append(":\n");
        for (String item : items) {
            sb.append("      - ").append(quote(item)).append('\n');
        }
    }

    /** Quotes only when the entry is not a safe bare YAML scalar. */
    static String quote(String s) {
        if (s != null && SAFE.matcher(s).matches()) {
            return s;
        }
        String q = s == null ? "" : s.replace("\\", "\\\\").replace("\"", "\\\"");
        return "\"" + q + "\"";
    }
}
